version: "3.5"

services:
  ffmpeg-go-server:
    image: necromant/ffmpeg-go-server
    hostname: ffmpeg-go-server
    restart: unless-stopped
    networks:
      - public
      - private
    configs:
      - source: ffmpeg_server_config
        target: /etc/ffmpeg-server/config.yaml
    volumes:
      - /media/hidrive/users/xhq6savpdkk9cruusg9a4najh/movies/:/media/conversion/
      - /home/admin/upload/:/media/upload/
      - ffmpeg_server_temp:/media/temp/
    secrets:
      - ffmpeg_db_password
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/ffmpeg_db_password
      - POSTGRES_USER=ffmpeg
    networks:
      - private
    secrets:
      - ffmpeg_db_password
    volumes:
      - ffmpeg_postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr


networks:
  private:
  public:
    external: true

secrets:
  ffmpeg_db_password:
    external: true

configs:
  ffmpeg_server_config:
    external: true

volumes:
  ffmpeg_postgres_data:
    external: true
  ffmpeg_server_temp:
    external: true
